spring:
  datasource:
    url: jdbc:mysql://localhost:3306/j9_bank_final_project
    username: ironhacker
    password: 1r0nh4ck3r
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  profiles:
    active: demo

server:
  port: 8080
